return PlaceObj('ModDef', {
	'title', "Force Delete",
	'description', "Delete what normal demolition cannot: stuck objects such as bugged train tracks, and advanced targets such as colonists, deposits, scenario decorations, etc.\n\n------------------------------------------------------------\n\nLevel 1 — Standard Force Delete\n\nFor normal demolishable objects. It uses the game’s standard demolition path when possible, making it the safer option.\n\nShortcuts:\n\nPC: Ctrl + Delete\nXbox [not tested]: LB + RB + X\nPlayStation [not tested]: L1 + R1 + Square\n------------------------------------------------------------\n\nLevel 2 — Advanced Force Delete\n\nFor harder cases that may need extra cleanup, including colonists, deposits, scenario decorations, and staged domes. This mode is more aggressive and may cause crashes, especially when deleting fully functioning domes.\n\nShortcuts:\n\nPC: Ctrl + Shift + Delete\nXbox [not tested]: LB + RB + Y\nPlayStation [not tested]: L1 + R1 + Triangle\n------------------------------------------------------------\n\nUpdated for Surviving Mars Relaunched v1.1.1.405907. Full in-game regression testing on this build is pending. Previously tested on v1.0.7 on Windows 11.\nPlease complain! I can’t fix what I don’t know is broken: https://github.com/facazevedo/SMR-force-delete/issues",
	'short_description', "Ctrl+Delete force-deletes the selected object.",
	'image', "Mod/ForceDelete/Images/force_delete.jpg",
	'last_changes', "Fixed survivors staying still after dome/container deletion: restart unit commands, retain healthy controllers and rover requests, and recover valid positions",
	'id', "ForceDelete",
	'author', "fredware",
	'version', 12,
	'lua_revision', 350453,
	'saved_with_revision', 405907,
	'code', {
		"Code/ForceDelete.lua",
		"Code/fd_config.lua",
		"Code/fd_display_attributes.lua",
		"Code/fd_colonist.lua",
		"Code/fd_drone.lua",
		"Code/fd_animal.lua",
		"Code/fd_shuttle.lua",
		"Code/fd_rover.lua",
		"Code/fd_train.lua",
		"Code/fd_rocket.lua",
		"Code/fd_deposit.lua",
		"Code/fd_decoration.lua",
		"Code/fd_infrastructure.lua",
		"Code/fd_internal_building.lua",
		"Code/fd_external_building.lua",
		"Code/fd_dome.lua",
	},
	'saved', 1791221730,
	'pdx_id', 144462,
	'pdx_version', "3",
	'steam_id', "3759755478",
	'TagInterface', true,
})