return PlaceObj('ModDef', {
	'title', "Force Delete",
	'description', "Delete what normal demolition cannot: stuck objects such as bugged train tracks, and advanced targets such as colonists, deposits, scenario decorations, etc.\n\n------------------------------------------------------------\n\nLevel 1 — Standard Force Delete\n\nFor normal demolishable objects. It uses the game’s standard demolition path when possible, making it the safer option.\n\nShortcuts:\n\nPC: Ctrl + Delete\nXbox [not tested]: LB + RB + X\nPlayStation [not tested]: L1 + R1 + Square\n------------------------------------------------------------\n\nLevel 2 — Advanced Force Delete\n\nFor harder cases that may need extra cleanup, including colonists, deposits, scenario decorations, and staged domes. This mode is more aggressive and may cause crashes, especially when deleting fully functioning domes.\n\nShortcuts:\n\nPC: Ctrl + Shift + Delete\nXbox [not tested]: LB + RB + Y\nPlayStation [not tested]: L1 + R1 + Triangle\n------------------------------------------------------------\n\nTested only on Surviving Mars Relaunched v1.0.7 on Windows 11.\nPlease complain! I can’t fix what I don’t know is broken: https://github.com/facazevedo/surviving-mars-relaunched-mods/issues",
	'short_description', "Ctrl+Delete force-deletes the selected object.",
	'image', "Mod/ForceDelete/Images/force_delete.jpg",
	'last_changes', "Fixed a Mod Manager load error by deferring Force Delete shortcut registration until the game shortcut host is ready",
	'id', "ForceDelete",
	'author', "fredware",
	'version', 10,
	'lua_revision', 350453,
	'saved_with_revision', 396349,
	'code', {
		"Code/ForceDelete.lua",
		"Code/fd_config.lua",
		"Code/fd_display_attributes.lua",
		"Code/fd_colonist.lua",
		"Code/fd_drone.lua",
		"Code/fd_animal.lua",
		"Code/fd_shuttle.lua",
		"Code/fd_rover.lua",
		"Code/fd_train.lua",
		"Code/fd_rocket.lua",
		"Code/fd_deposit.lua",
		"Code/fd_decoration.lua",
		"Code/fd_infrastructure.lua",
		"Code/fd_internal_building.lua",
		"Code/fd_external_building.lua",
		"Code/fd_dome.lua",
	},
	'saved', 1783435952,
	'code_hash', -8272021352788548032,
	'pdx_id', 144462,
	'pdx_version', "3",
	'steam_id', "3759755478",
	'TagInterface', true,
})